### PR TITLE
Add exercise instructions and tests

### PR DESCRIPTION
**Pull request by thomastuts**
Would love some feedback here on testing. The tests aren't very extensive, but just plainly checking the DOM strings for equality does give good testing output for the students to use. The other way we could do this is to check each element separately to see if it has the right tag and content (and optionally a class too), but that seems like a hassle for barely any gain, if any.

### CODE REVIEW

**Comment by ezmiller** [comment]
@thomastuts, I tend to agree with you here that there's not much reason to make the testing more extensive in terms of the content. The goal here is to familiarize the student with creating components using both `React.createClass()` and the ES2015 `class` syntax, right? If so, it seems as though your tests cover that pretty well, no?

**Comment by thomastuts** [comment]
@ezmiller Yeah, the tests cover everything in the lab and should be pretty easy to follow for the students because of the diff output of the strings. I think we're good here, just wanted a second opinion to make sure I'm not missing a better way. Thanks for the quick reply!

**Comment by ezmiller** [comment]
@thomastuts No problem. I mean the only thing that I can think of is that you might want to construct the tests more loosely. Like use `to.contain()` to check for the text you wanted. But in the lab you are asking for a specific html output, so what you did makes perfect sense. Beyond that  my only question would be whether the test being so specific could lead it to be more brittle than it needs to be. Is it possible that the user could essentially do the lab correctly in terms of generating the right html output and yet fail the test because of some quirk about how the html is rendered as a string?

**Comment by thomastuts** [comment]
I don't think so. The output from `.html()` is stripped of any insignificant whitespace, and I used that  output string as the expected result (including the escaped single quote).

**Comment by ezmiller** [comment]
@thomastuts then I think this is ready to 🚢

**Pull request merged**
